### PR TITLE
Fix creates entry during install step

### PR DESCRIPTION
**Pull request by jobevers**
Otherwise the install step takes a long time.

### CODE REVIEW

**Comment by tersmitten** [comment]
This indeed looks more correct. What (PyCharm) version are you using? Did the zip file (content) change?

**Comment by jobevers** [comment]
community edition, 2017.3.4

Without the correct `creates`, ansible tries to unarchive again.  The contents are unchanged and the job reports back as being unchanged.  It just takes a while.

**Comment by tersmitten** [comment]
I understand what `creates` does, but this I think that the zip files of earlier version look different.

**Comment by tersmitten** [comment]
```sh
mtersmitten@ares:/var/lib/ansible/pycharm/downloads
# tar --list --verbose --file=pycharm-professional-4.5.5.tar.gz | sort | head
-rw-r--r-- 0/0               0 2016-05-01 16:02 pycharm-4.5.5/helpers/pycharm/__init__.py
-rw-r--r-- 0/0               0 2016-05-01 16:02 pycharm-4.5.5/helpers/pydev/pydevd_plugins/__init__.py
-rw-r--r-- 0/0               0 2016-05-01 16:02 pycharm-4.5.5/helpers/pydev/_pydev_imps/__init__.py
-rw-r--r-- 0/0               0 2016-05-01 16:02 pycharm-4.5.5/helpers/pydev/pydev_ipython/__init__.py
-rw-r--r-- 0/0               0 2016-05-01 16:02 pycharm-4.5.5/helpers/python-skeletons/asyncio/__init__.py
-rw-r--r-- 0/0           10005 2016-05-01 16:02 pycharm-4.5.5/helpers/coverage/results.py
-rw-r--r-- 0/0           10011 2016-05-01 16:02 pycharm-4.5.5/helpers/pydev/third_party/pep8/lib2to3/lib2to3/btm_utils.py
-rw-r--r-- 0/0          100137 2016-05-01 16:02 pycharm-4.5.5/helpers/pydev/pydevd.py
-rw-r--r-- 0/0             100 2016-05-01 16:02 pycharm-4.5.5/helpers/coverage/__main__.py
-rw-r--r-- 0/0             100 2016-05-01 16:02 pycharm-4.5.5/helpers/pydev/pydev_pysrc.py
```

**Comment by tersmitten** [comment]
Can you think of a way to support both situations?

https://www.jetbrains.com/pycharm/download/previous.html

**Comment by jobevers** [comment]
Ah, sorry, I mis-understood your question.

```
/var/lib/ansible/pycharm/downloads$ tar --list --verbose --file=pycharm-community-2017.3.4.tar.gz | sort | head
-rw-r--r-- 0/0               0 2018-03-06 12:37 pycharm-community-2017.3.4/helpers/profiler/_imps/__init__.py
-rw-r--r-- 0/0               0 2018-03-06 12:37 pycharm-community-2017.3.4/helpers/profiler/thriftpy/contrib/__init__.py
-rw-r--r-- 0/0               0 2018-03-06 12:37 pycharm-community-2017.3.4/helpers/pycharm/__init__.py
-rw-r--r-- 0/0               0 2018-03-06 12:37 pycharm-community-2017.3.4/helpers/pycharm_matplotlib_backend/__init__.py
-rw-r--r-- 0/0               0 2018-03-06 12:37 pycharm-community-2017.3.4/helpers/pydev/_pydev_bundle/__init__.py
-rw-r--r-- 0/0               0 2018-03-06 12:37 pycharm-community-2017.3.4/helpers/pydev/_pydevd_bundle/__init__.py
-rw-r--r-- 0/0               0 2018-03-06 12:37 pycharm-community-2017.3.4/helpers/pydev/pydevd_concurrency_analyser/__init__.py
-rw-r--r-- 0/0               0 2018-03-06 12:37 pycharm-community-2017.3.4/helpers/pydev/_pydevd_frame_eval/__init__.py
-rw-r--r-- 0/0               0 2018-03-06 12:37 pycharm-community-2017.3.4/helpers/pydev/_pydev_imps/__init__.py
-rw-r--r-- 0/0               0 2018-03-06 12:37 pycharm-community-2017.3.4/helpers/pydev/pydev_ipython/__init__.py
```

**Comment by tersmitten** [comment]
Maybe something with `version_compare` based on `pycharm_version`?

**Comment by tersmitten** [comment]
Fixed in https://github.com/Oefenweb/ansible-pycharm/releases/tag/v2.0.0

**Pull request closed without merging**
